### ISSUE TITLE
Integration with SynthSeg

### ISSUE THREAD

**Issue by jaivardhankapoor** [Deep-MI/BrainPrint-python#6]
Hi,

Is there ongoing work on integrating the library with [SynthSeg](https://github.com/BBillot/SynthSeg) neural net-based segmentation software? this would possibly massively speed up analyses.

**Comment by m-reuter** [comment]
Hi, everything that delivers a FreeSurfer-like output (with the same label ids etc) should work. 

Note, that we distribute [FastSurfer](https://github.com/deep-mi/FastSurfer) which is performing the segmentation in less than 1 minute and is recommended over SynthSeg for T1 images of resolutions from .6 to around 1.2mm as it outperforms SynthSeg by a margin. For lower resolutions and other sequences than T1, SynthSeg is best.

**Comment by m-reuter** [comment]
[Comparison-SynthSeg-FastSurfer.pdf](https://github.com/Deep-MI/BrainPrint-python/files/10900288/Comparison-SynthSeg-FastSurfer.pdf)
Here we show a head-to-head comparison of different versions of FastSurfer and Synthseg on the Mindboggle (manual) and a few other test datasets.
